### ISSUE TITLE
details on how to run this?

### ISSUE THREAD

**Issue by PrincyX** [huberemanuel/anomaly-gan-av#2]

**Comment by huberemanuel** [comment]
Hello sir,
The actual code only trains a DCGAN model on mnist or with collected data of an RC car running the DonkeyCar software, you can run it with a simple ` python3 main.py ` and pass some parameters if needed.
My first assumption on anomaly detection with GANs relied on only using the Discriminator output as the anomaly score, but this is conceptually wrong as highlighted by Goodfellow https://www.quora.com/Do-generative-adversarial-networks-function-for-outlier-detection
If you want to do anomaly detection with GANs, I recommend the following works, all of them have implementations on Github:
ALAD - https://arxiv.org/pdf/1812.02288.pdf
AnoGAN - https://arxiv.org/pdf/1703.05921.pdf
Fence GAN - https://arxiv.org/pdf/1904.01209.pdf
ALOCC - https://arxiv.org/pdf/1802.09088.pdf

**Comment by PrincyX** [comment]
just curious, what/how were your results?

**Comment by huberemanuel** [comment]
Really bad, as expected.
![image](https://user-images.githubusercontent.com/6238718/61265856-ab118400-a768-11e9-833b-7d12f5f50bc7.png)
